language: java

addons:
  sonarcloud:
    organization: "udev12"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=udev12_gauge_acceptance_test_example